name: jordanhamilton
favicon: null
layout_spectrum: 0.3768630027770996
typography_spectrum: 0.9917929118964821
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.09129095706157386
  lightness: 0.016584833152592182
  saturation: 0.8010651681106538
  rhythmicContrast: 0.042578388238325715
purpose: []
